import { library } from '@fortawesome/fontawesome-svg-core';
import { faEye, faEyeSlash } from '@fortawesome/free-regular-svg-icons';
import {
  faSignOutAlt,
  faCheck,
  faTasks,
  faEnvelopeOpenText,
  faUser,
  faUsers,
  faUserCheck,
  faUserMinus,
  faUserAltSlash,
  faArrowDown,
  faArrowUp,
  faSpinner,
  faImage,
  faTimes,
  faExclamation,
  faSearch,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faEye,
  faEyeSlash,
  faSignOutAlt,
  faCheck,
  faTasks,
  faEnvelopeOpenText,
  faUser,
  faUsers,
  faUserCheck,
  faUserMinus,
  faUserAltSlash,
  faArrowDown,
  faArrowUp,
  faSpinner,
  faImage,
  faTimes,
  faExclamation,
  faSearch,
);
